{{ Html::script('assets/plugins/pace/pace.min.js') }}
{{ Html::script('assets/plugins/jquery/jquery-1.11.1.min.js') }}
{{ Html::script('assets/plugins/modernizr.custom.js') }}
{{ Html::script('assets/plugins/jquery-ui/jquery-ui.min.js') }}
{{ Html::script('assets/plugins/boostrapv3/js/bootstrap.min.js') }}
{{ Html::script('assets/plugins/jquery/jquery-easy.js') }}
{{ Html::script('assets/plugins/jquery-unveil/jquery.unveil.min.js') }}
{{ Html::script('assets/plugins/jquery-bez/jquery.bez.min.js') }}
{{ Html::script('assets/plugins/jquery-ios-list/jquery.ioslist.min.js') }}
{{ Html::script('assets/plugins/jquery-actual/jquery.actual.min.js') }}
{{ Html::script('assets/plugins/jquery-scrollbar/jquery.scrollbar.min.js') }}
{{ Html::script('assets/plugins/bootstrap-select2/select2.min.js') }}
{{ Html::script('assets/plugins/classie/classie.js') }}
{{ Html::script('assets/plugins/switchery/js/switchery.min.js') }}
{{ Html::script('assets/plugins/nvd3/lib/d3.v3.js') }}
{{ Html::script('assets/plugins/nvd3/nv.d3.min.js') }}
{{ Html::script('assets/plugins/nvd3/src/utils.js') }}
{{ Html::script('assets/plugins/nvd3/src/tooltip.js') }}
{{ Html::script('assets/plugins/nvd3/src/interactiveLayer.js') }}
{{ Html::script('assets/plugins/nvd3/src/models/axis.js') }}
{{ Html::script('assets/plugins/nvd3/src/models/line.js') }}
{{ Html::script('assets/plugins/nvd3/src/models/lineWithFocusChart.js') }}
{{ Html::script('assets/plugins/mapplic/js/hammer.js') }}
{{ Html::script('assets/plugins/mapplic/js/jquery.mousewheel.js') }}
{{ Html::script('assets/plugins/mapplic/js/mapplic.js') }}
{{ Html::script('assets/plugins/jquery-metrojs/MetroJs.min.js') }}
{{ Html::script('assets/plugins/jquery-sparkline/jquery.sparkline.min.js') }}
{{ Html::script('assets/plugins/skycons/skycons.js') }}
{{ Html::script('assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js') }}
{{ Html::script('assets/pages/js/pages.min.js') }}
{{ Html::script('assets/js/scripts.js') }}